### ISSUE TITLE
API definition

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Root#6]

**Comment by a-a-hofmann** [comment]
/api/courses/
/api/courses/{courseId}

/api/courses/{courseId}/assignments/
/api/courses/{courseId}/assignments/{assignmentId}

/api/courses/{courseId}/assignments/{assignmentId}/exercises
/api/courses/{courseId}/assignments/{assignmentId}/exercises/{id}

- Send course
- Send assignment
- Send exercise
- Files are sent as string

**Comment by Haeri** [comment]
https://github.com/mp-access/Course-Service/wiki/Course-Service-API
